title = "DER Jeofizik"
channel_id = "UCJjDSNZrtrKTmlNjAjuhP0Q"
base_url = "https://derjeofizik.github.io"
template_dir = "templates"
output_dir = "output"
pages_dir = "pages"
include_dir = "templates/include"
deploy_dir = "derjeofizik.github.io"

[extra_notes]
6D_Lo6ti9OY = "notes/karayip.md"
mNXMjcQuIwg = "notes/maras.md"

[authors]

[authors.dertuncay]
name = "Deniz Ertuncay"
info = '''Lisans eğitimini İstanbul Üniversitesi Jeofizik Mühendisliği bölümünden, yüksek lisansını Boğaziçi Üniversitesi Kandilli Rasathanesi ve Deprem Araştırma Enstitüsü Jeofizik bölümünden aldı. Doktorasını 2020 yılında Trieste Üniversitesi Yer Bilimleri ve Matematik bölümünden aldı ve şu anda aynı bölümde doktora sonrası araştırmacı olarak çalışmalarını sürdürüyor.

Araştırma konuları: deprem yakın kaynak alanındaki sismik hareketler, sismolojide yapay zeka uygulamaları ve sismik izleme.

TMMOB Jeofizik Mühendisleri Odası XIII ve XIV dönem yönetim kurullarında yer aldı.'''
photo = "deniz_ertuncay.jpeg"

[[authors.dertuncay.links]]
name = "Web Sitesi"
url = "https://dertuncay.wixsite.com/denizertuncay"

[[authors.dertuncay.links]]
name = "Twitter"
url = "https://twitter.com/dertuncay"

[authors.ebekin]
name = "Ekrem Bekin"
info = '''Lisans Eğitimini İstanbul Üniversitesi Jeofizik Mühendisliği bölümünden aldı.
1. yüksek lisans derecesini Boğaziçi Üniversitesi Kandilli Rasathanesi ve Deprem Araştırma Enstitüsü Jeofizik Bölümünden,
2. yüksek lisans derecesini Memorial University of Newfoundland'tan aldı.
2016 yılından beri İstanbul Üniversitesi-Cerrahpaşa Jeofizik Mühendisliği Bölümünde
doktora öğrencisidir.

Araştırma Konuları: manyetotellürik yöntem, zemin sıvılaşması '''
photo = "ekrem_bekin.jpeg"

[[authors.ebekin.links]]
name = "Twitter"
url = "https://twitter.com/ekrembekin"

[[authors.ebekin.links]]
name = "Github"
url = "https://github.com/ekrembkn"


[authors.gizgi]
name = "Gizem İzgi"
info = '''Lisans eğitimini 2017, yüksek lisans eğitimini 2019 yılında İstanbul Teknik Üniversitesi Jeofizik Mühendisliği bölümünde tamamladı. 2019 yılından itibaren doktorasına Potsdam Üniversitesi Yer Bilimleri Enstitüsünde başladı ve halen devam ediyor.

Araştırma konuları: coda dalgaları, sismik sönümlenme, rotasyonel (dönel) sismoloji ve deprem lokasyonu.

İTÜ Mezunlar Derneği bünyesinde iki dönemdir mentorlük ve mentor danışmanlığı görevini yapmakta.'''
photo = "gizem_izgi.jpeg"

[[authors.gizgi.links]]
name = "Twitter"
url = "https://twitter.com/izgizem"

[[authors.gizgi.links]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/gizem-izgi-562b877a"

[[authors.gizgi.links]]
name = "ResearchGate"
url = "https://www.researchgate.net/profile/Gizem_Izgi"

[authors.rorsvuran]
name = "Rıdvan Örsvuran"
info = '''Lisans Eğitimini İstanbul Üniversitesi Jeofizik Mühendisliğinden, yüksek lisansını Boğaziçi Üniversitesi Kandilli Rasathanesi ve Deprem Araştırma Enstitüsü Jeofizik bölümünden aldı. Doktorasını Université Côte d'Azur'da
yaptı. Colorado School of Mines Jeofizik bölümünde doktora sonrası araştırmacı olarak çalışmalarını sürdürüyor.

Araştırma konuları: sismik tomografi, deprem kaynak mekanizmaları,  sayısal yöntemler, yüksek performans bilgi-işlem.'''
photo = "ridvan_orsvuran.jpg"

[[authors.rorsvuran.links]]
name = "Web Sitesi"
url = "https://rdno.org"

[[authors.rorsvuran.links]]
name = "Twitter"
url = "https://twitter.com/rdn0"